version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started on `date`
      - echo sample test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - ls
      - ls target
      - printf '{"ImageURI":"tomcat:jdk8-adoptopenjdk-openj9"}' > imageDetail.json
artifacts:
  files:
    - target/SpringBootMavenExample-1.3.5.RELEASE.war
    - imageDetail.json
  discard-paths: yes
